[versions]
android-compileSdk = "35"
android-buildTools = "34.0.0"
android-minSdk = "23"
android-targetSdk = "35"
android-tools = "8.7.3"
kotlinx-coroutines = "1.9.0"
androidx-appCompat = "1.7.0"
androidx-contraintLayout = "2.2.0"
androidx-core = "1.15.0"
androidx-datastore = "1.1.2"
androidx-fragment = "1.8.5"
androidx-lifecycle = "2.8.7"
androidx-navigation = "2.8.5"
androidx-work = "2.10.0"
google-material = "1.12.0"
google-services = "4.4.2"
auth0 = "2.11.0"
glide = "4.16.0"
moshi = "1.15.2"
notificare-services = "1.1.0"
retrofit = "2.11.0"
timber = "5.0.1"


[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-contraintLayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
auth0 = { module = "com.auth0.android:auth0", version.ref="auth0" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref="retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref="retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-tools" }
notificare-services = { id = "re.notifica.gradle.notificare-services", version.ref = "notificare-services" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

[bundles]
androidx-lifecycle = ["androidx-lifecycle-livedata", "androidx-lifecycle-runtime", "androidx-lifecycle-viewModel"]
androidx-navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]
retrofit = ["retrofit", "retrofit-scalars"]
