[versions]
maven-artifactGroup = "com.actito"
maven-artifactVersion = "5.0.0-canary.3"
android-library = "8.13.0"
android-compileSdk = "36"
android-buildTools = "35.0.0"
android-minSdk = "23"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
androidx-activity = "1.11.0"
androidx-appCompat = "1.7.1"
androidx-browser = "1.9.0"
androidx-cardView = "1.0.0"
androidx-contraintLayout = "2.2.1"
androidx-core = "1.17.0"
androidx-exifInterface = "1.4.1"
androidx-fragment = "1.8.9"
androidx-lifecycle = "2.9.4"
androidx-room = "2.8.1"
androidx-test-core = "1.7.0"
androidx-viewPager = "1.1.0"
androidx-work = "2.10.5"
altbeacon = "2.21.1"
glide = "5.0.5"
google-ksp = "2.2.20-2.0.4"
google-androidInstallReferrer = "2.2"
google-firebase-messaging = "25.0.1"
google-playServices-base = "18.9.0"
google-playServices-location = "21.3.0"
google-playServices-maps = "19.2.0"
moshi = "1.15.2"
okhttp = "5.2.0"
detekt = "1.23.8"
junit = "4.13.2"
ktlint = "12.3.0"
mavenPublish = "0.34.0"
mockito = "5.20.0"
robolectric = "4.16"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-playServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-cardView = { module = "androidx.cardview:cardview", version.ref = "androidx-cardView" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-contraintLayout" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-exifInterace = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifInterface" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-viewPager = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewPager" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core"}
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
altbeacon = { module = "org.altbeacon:android-beacon-library", version.ref = "altbeacon"}
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
google-androidInstallReferrer = { module = "com.android.installreferrer:installreferrer", version.ref = "google-androidInstallReferrer" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "google-firebase-messaging" }
google-playServices-base = { module = "com.google.android.gms:play-services-base", version.ref = "google-playServices-base" }
google-playServices-location = { module = "com.google.android.gms:play-services-location", version.ref = "google-playServices-location"}
google-playServices-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "google-playServices-maps" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
junit = { module = "junit:junit", version.ref = "junit"}
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito"}
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }

[bundles]
androidx-lifecycle = ["androidx-lifecycle-livedata", "androidx-lifecycle-process"]
androidx-room = ["androidx-room", "androidx-room-runtime"]
moshi = ["moshi", "moshi-adapters"]
okhttp = ["okhttp", "okhttp-loggingInterceptor"]
